'use client';
import Link from 'next/link';
import { NavigationLink } from './navigation-link';
import { usePathname } from 'next/navigation';
import { useState } from 'react';
import { signOut } from '@/app/auth/actions';
import { LayoutDashboard, ArrowLeftRight, Upload, Sparkles, FileText, Settings, PanelLeftClose, Menu, ChevronDown, ArrowUpRight, ScanLine } from 'lucide-react';
const nav=[{href:'/dashboard',label:'Overview',icon:LayoutDashboard},{href:'/trades',label:'Trades',icon:ArrowLeftRight},{href:'/import',label:'Import trades',icon:Upload},{href:'/insights',label:'Review',icon:Sparkles},{href:'/reports',label:'Reports',icon:FileText},{href:'/settings',label:'Settings',icon:Settings}];
export function Logo({href="/"}:{href?:string}){return <Link href={href} className="logo"><span className="logo-icon"><ScanLine size={22}/></span>TradeMirror<span className="logo-dot">.</span></Link>;}
export function Shell({children,account}:{children:React.ReactNode;account?:{name:string;email:string}|null}) {const path=usePathname();const [open,setOpen]=useState(false);const demo=path.startsWith('/demo');const navigation=demo?nav.map(n=>({...n,href:n.href==='/dashboard'?'/demo':n.href==='/insights'?'/demo/review':['/import','/settings'].includes(n.href)?'/signup':'/demo'+n.href})):nav;const active=(href:string)=>href==='/demo'?path==='/demo':path.startsWith(href);const current=navigation.find(n=>active(n.href));return <div className="app-shell"><aside className={open?'sidebar open':'sidebar'}><div className="sidebar-brand"><Logo href={demo?'/':'/dashboard'}/><button className="icon-button mobile-only" onClick={()=>setOpen(false)} aria-label="Close navigation"><PanelLeftClose size={20}/></button></div><div className="workspace"><span className="avatar">D</span><div><b>{account?'Your workspace':'Demo workspace'}</b><small>Personal trading journal</small></div><ChevronDown size={15}/></div><p className="nav-caption">WORKSPACE</p><nav>{navigation.map(n=><NavigationLink onClick={()=>setOpen(false)} key={n.label} href={n.href} className={active(n.href)?'nav-item active':'nav-item'}><n.icon size={18}/>{n.label}</NavigationLink>)}</nav><div className="sidebar-bottom"><div className="demo-note"><span className="live-dot"/><b>A clearer view of your edge</b><p>{account?'CSV imports are ready. Review your saved executions.':'Explore sample analytics. Sign up to import and review your own trading history.'}</p><Link href={demo?"/signup":"/import"}>Explore imports <ArrowUpRight size={14}/></Link></div><Link href={demo?"/signup":"/settings"} className="profile"><span className="avatar">DT</span><div><b>{account?.name||'Demo trader'}</b><small>{account?.email||'Preview account'}</small></div><Settings size={16}/></Link></div></aside>{open&&<button className="nav-backdrop" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}<div className="main-wrap"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-only" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu size={21}/></button><span>Workspace</span><span className="slash">/</span><b>{path.startsWith('/trades/')?'Trade detail':current?.label||(path==='/demo'?'Interactive demo':'Workspace')}</b></div><div className="top-actions"><span className="sync-status"><span className="live-dot"/>{account?'Account connected':'Demo mode'}</span>{account&&<form action={signOut}><button className="text-button" type="submit">Sign out</button></form>}<span className="avatar small">DT</span></div></header><main className="main-content">{children}<footer className="app-footer"><span>TradeMirror · A better understanding of your trading.</span><span>{account?'Your account · All times IST':'Sample data · All times IST'}</span></footer></main></div></div>;}
