import Link from 'next/link';
import {StrategyComparison} from './strategy-comparison';
import {Card} from '@/components/ui/primitives';
import {strategyReview} from '@/lib/journal/strategy';
import {exactMoney} from '@/lib/analytics/format';
import type {Match} from '@/lib/analytics/matching';
export function StrategyReview({matches,tags,status,error,demo=false}:{matches:Match[];tags:Record<string,string[]>;status?:{linked:number;outsideScope:number;unlinked:number};error?:string;demo?:boolean}){
 const review=strategyReview(matches,tags);const href=demo?'/demo/trades':'/trades';
 return <section className="strategy-review"><Card><div className="section-title"><div><span className="eyebrow">YOUR LABELS, YOUR REVIEW</span><h2>Which setups are showing up?</h2><p>Performance grouped by journal tags · realized gross · current imported history</p></div><Link className="button secondary" href={href}>Open journal</Link></div>{error?<p className="inline-notice" role="alert">{error} Strategy results are unavailable until tags load.</p>:<><div className="strategy-coverage"><span><b>{review.tagged}</b> tagged slices</span><span><b>{review.untagged}</b> without tags</span><span><b>{review.groups.length}</b> tags</span></div><p className="fineprint">Tags are your own labels, not verified strategies. A slice with multiple tags appears in each group; group totals overlap and must not be added together. Small samples do not establish an edge. Charges and net P&L are unavailable.</p>{review.groups.length?<><div className="table-scroll strategy-table"><table><thead><tr><th>Journal tag</th><th>Slices</th><th>Win rate</th><th>Profit factor</th><th>Avg gross / slice</th><th>Gross P&L</th><th>Review</th></tr></thead><tbody>{review.groups.map(({tag,summary:s})=><tr key={tag}><td><span className="tag-chip">{tag}</span></td><td>{s.slices}{s.slices<20&&<small className="strategy-sample">Small sample</small>}</td><td>{s.winRate}%</td><td>{s.profitFactor||'No gross losses'}</td><td>{exactMoney(s.expectancy||'0')}</td><td className={s.grossPnl.startsWith('-')?'negative':'positive'}>{exactMoney(s.grossPnl)}</td><td><Link className="text-link" href={`${href}?${new URLSearchParams({tag})}`}>View slices →</Link></td></tr>)}</tbody></table></div><StrategyComparison groups={review.groups} journalHref={href}/></>:<div className="strategy-empty"><h3>Start with a label that matters to you.</h3><p>Open a matching slice, add a tag such as breakout or planned exit, and save your journal. Its recorded results will appear here.</p><Link className="button primary" href={href}>Tag your first slice</Link></div>}</> }</Card>{!demo&&!error&&status&&<Card><h2>Saved-note connection status</h2><div className="strategy-coverage"><span><b>{status.linked}</b> linked to this history</span><span><b>{status.outsideScope}</b> outside this scope</span><span><b>{status.unlinked}</b> without a current matching slice</span></div><p className="fineprint">Outside-scope notes still match the full saved history, including excluded examples. Unlinked notes are retained: their exact matching evidence is absent from the current full history. This can happen when FIFO results change; it does not prove the note or import is invalid. No notes are deleted or moved automatically.</p>{status.unlinked>0&&<p className="inline-notice">Review your import history before creating fresh notes on changed results. Restoring the original matching evidence reconnects the existing notes. Manual comparison and reassignment remain planned.</p>}</Card>}</section>;
}
