import {ReviewRange} from '@/components/dashboard/review-range';
import {reviewRange} from '@/lib/journal/range';
import {journalTags} from '@/lib/journal/index';
import {StrategyReview} from '@/components/dashboard/strategy-review';
import { getWorkspaceAccount } from '@/lib/auth/session';
import { getAccountAnalytics } from '@/lib/workspace/analytics';
import { AccountReview } from '@/components/dashboard/account-review';
import { Sparkles,ArrowUpRight } from 'lucide-react';
import { insights } from '@/data/mock';
import { Card } from '@/components/ui/primitives';
export default async function Insights({searchParams}:{searchParams:Promise<{start?:string;end?:string}>}){const query=await searchParams;const account=await getWorkspaceAccount();if(account){let analytics;let failure='';try{analytics=await getAccountAnalytics();}catch(error){failure=error instanceof Error?error.message:'Unable to load review.';}if(!analytics)return <p className="inline-notice" role="alert">{failure}</p>;const range=reviewRange(analytics.result.matches,query.start,query.end);let journal:Awaited<ReturnType<typeof journalTags>>;try{const full=await getAccountAnalytics(true);journal=await journalTags({...analytics.result,matches:range.matches},full.result);}catch{journal={tags:{},error:'Saved-note connections could not be checked. Refresh to retry.'};}return <><div className="page-heading"><div><span className="eyebrow">PATTERNS, NOT PREDICTIONS</span><h1>Your history, explained.</h1><p>Computed performance review · real imports only · charges excluded.</p></div></div><ReviewRange start={range.start} end={range.end} error={range.error} href="/insights"/><StrategyReview start={range.start} end={range.end} matches={range.matches} tags={journal.tags} status={journal.status} error={range.error||journal.error}/><AccountReview result={analytics.result}/></>;}return <><div className="page-heading"><div><span className="eyebrow">PATTERNS, NOT PREDICTIONS</span><h1>Your trading, reflected.</h1><p>A thoughtful review of your behaviour. Sample week · 1–7 October.</p></div><span className="badge neutral"><Sparkles size={13}/>Sample insights</span></div><div className="insight-hero"><Sparkles size={28}/><span className="eyebrow">THIS WEEK’S REFLECTION</span><h2>Good mornings.<br/><span className="muted">A tougher final hour.</span></h2><p>Your early session contributed most of the sample week’s profit. Start your review with what changed later in the day.</p><span className="badge neutral">Illustrative analysis · No AI API connected</span></div><div className="two-col insights-grid">{insights.map((x,i)=><Card key={x.id}><div className="spread"><span className="eyebrow">{x.category}</span><span className="insight-number">0{i+1}</span></div><h2>{x.title}</h2><p>{x.body}</p><span className="text-link">Sample observation <ArrowUpRight size={14}/></span></Card>)}</div></>;}
