'use client';
import {useState} from 'react';
import {generateAiReview} from '@/app/reports/ai-actions';
import {downloadJson} from './saved-reports';
import type {ReportMode} from '@/lib/reports/snapshot';
import type {AiReview,reviewEvidence} from '@/lib/reports/ai';
export function AiPeriodReview({mode,date,demo=false}:{mode:ReportMode;date?:string;demo?:boolean}){
 const [consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[review,setReview]=useState<{data:AiReview;evidence:ReturnType<typeof reviewEvidence>;period:string;mode:ReportMode}|null>(null);
 async function generate(){if(!date)return;setBusy(true);setError('');try{const result=await generateAiReview(mode,date,consent);if(result.error)setError(result.error);else if(result.data&&result.evidence)setReview({data:result.data,evidence:result.evidence,period:date,mode});}catch{setError('Unable to generate review. Retry.');}finally{setBusy(false);}}
 return <section><h2>AI-assisted period reflection</h2><p>Ask for three review prompts grounded in this period’s computed gross metrics.</p>{demo?<p className="inline-notice">AI generation is account-only and requires server setup. No demo data is sent to OpenAI.</p>:<><label className="ai-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Share this period’s computed results, counts, holding time and gross drawdown with OpenAI. Raw CSV, execution IDs, email, notes and tags are excluded.</label><p className="fineprint">Requires configured server API key/model. Five attempts per UTC day, at least 90 seconds apart. API usage may incur provider charges. AI text can be wrong; inspect the supplied evidence. The request disables response storage; provider data policies still apply.</p><button className="button primary" disabled={!consent||busy||!date} onClick={generate}>{busy?'Generating reflection…':'Generate AI reflection'}</button>{error&&<p role="alert" className="inline-notice">{error}</p>}{review&&<div className="ai-result"><h3>{review.mode} reflection · {review.period}</h3>{review.data.observations.map((o,i)=><article key={i}><h3>{o.reflection}</h3><p>{o.question}</p><p className="fineprint">Recorded evidence: {review.evidence.find(e=>e.id===o.evidence_id)?.fact}</p></article>)}<button className="button secondary" onClick={()=>downloadJson({format:'trademirror-ai-review',version:1,...review},`trademirror-ai-review-${review.period}.json`)}>Download reflection JSON</button><p className="fineprint">This generated reflection is page-local until downloaded; it is not stored as a report snapshot.</p></div>}</>}</section>;
}
