'use client';
import {useState} from 'react';
import {previewStatement,saveStatement,loadStatements,type StatementRecord} from '@/app/costs/actions';
import {reconcileStatement,type BrokerStatement} from '@/lib/costs/zerodha';
import {exactMoney} from '@/lib/analytics/format';
import {Card} from '@/components/ui/primitives';
import {downloadJson} from './saved-reports';
import type {Match} from '@/lib/analytics/matching';
export function StatementDetail({statement,matches,demo=false}:{statement:BrokerStatement;matches:Match[];demo?:boolean}){const r=reconcileStatement(statement,matches);return <><h2>{demo?'Illustrative F&O statement':'Zerodha F&O'} · {statement.start} to {statement.end}</h2><div className="metric-grid advanced-metrics">{[[demo?'Illustrative realized gross':'Broker-reported realized gross',statement.gross],['Reported charges',statement.charges],['Other credits less debits',statement.otherNet],['Statement realized net',statement.net]].map(([label,value])=><div className="metric-card" key={label}><p>{label}</p><h3 className={value.startsWith('-')?'negative':'positive'}>{exactMoney(value)}</h3></div>)}</div><p className="fineprint">Statement realized net = reported realized gross − reported charges + other credits/debits. Unrealized P&L ({exactMoney(statement.unrealized)}) is excluded. {demo?'This is a fictional demonstration statement;':'This is an uploaded broker report;'} it is not independently certified and does not allocate costs to days or matching slices.</p><p className="inline-notice">{r.aligned?'Imported realized gross aligns by instrument for this period.':'Imported execution results do not fully align with this statement. Review missing history and settlement treatment before attributing these costs to your executions.'} Imported: {exactMoney(r.importedGross)} across {r.slices} slices.</p>{r.differences.length>0&&<div className="table-scroll strategy-table"><table><thead><tr><th>Instrument</th><th>Imported gross</th><th>Statement gross</th></tr></thead><tbody>{r.differences.map(d=><tr key={d.symbol}><td>{d.symbol}</td><td>{exactMoney(d.importedGross)}</td><td>{exactMoney(d.statementGross)}</td></tr>)}</tbody></table></div>}<details><summary>Charge breakdown</summary><div className="table-scroll"><table><thead><tr><th>Charge</th><th>Amount</th></tr></thead><tbody>{statement.chargeItems.map(c=><tr key={c.label}><td>{c.label}</td><td>{exactMoney(c.amount)}</td></tr>)}</tbody></table></div></details></>;}
export function CostStatements({matches}:{matches:Match[]}){const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<BrokerStatement|null>(null),[confirmed,setConfirmed]=useState(false),[rows,setRows]=useState<StatementRecord[]>([]),[selected,setSelected]=useState<StatementRecord|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 function form(){const data=new FormData();if(file)data.set('file',file);if(confirmed)data.set('confirmed','yes');return data;}
 async function inspect(){setBusy(true);setMessage('');setPreview(null);setConfirmed(false);try{const r=await previewStatement(form());if(r.error)setMessage(r.error);else setPreview(r.data||null);}catch{setMessage('Could not preview this report. Retry.');}finally{setBusy(false);}}
 async function save(){setBusy(true);setMessage('');try{const r=await saveStatement(form());if(r.error)setMessage(r.error);else if(r.data){const saved=r.data;setRows(old=>[saved,...old.filter(x=>x.id!==saved.id)].slice(0,20));setSelected(saved);setMessage('Statement saved. Identical files reuse the saved record. Execution history is unchanged.');}}catch{setMessage('Could not save statement. Retry.');}finally{setBusy(false);}}
 async function load(){setBusy(true);setMessage('');try{const r=await loadStatements();if(r.error)setMessage(r.error);else{setRows(r.data||[]);setSelected(r.data?.[0]||null);if(!r.data?.length)setMessage('No saved statements yet. Preview a broker P&L XLSX above.');}}catch{setMessage('Could not load statements. Retry.');}finally{setBusy(false);}}
 return <><Card><h2>Import broker costs</h2><p>Choose the original Zerodha Console F&O P&L XLSX. Charges, realized instrument totals and other debit/credit details must reconcile inside the file.</p><label className="statement-file">P&L XLSX · up to 5 MB<input type="file" accept=".xlsx" disabled={busy} onChange={e=>{setFile(e.target.files?.[0]||null);setPreview(null);setConfirmed(false);setMessage('');}}/></label><button className="button secondary" disabled={busy||!file} onClick={inspect}>{busy?'Working…':'Preview statement'}</button><p className="fineprint">Preview sends the file to this app for validation without saving. Save stores parsed totals/breakdowns; the original file and client ID are not stored. Other brokers and segments are not yet supported.</p>{preview&&<><StatementDetail statement={preview} matches={matches}/><label className="ai-consent"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>This F&O statement belongs to the Zerodha account whose history I imported.</label><button className="button primary" disabled={busy||!confirmed} onClick={save}>Save statement</button></>}{message&&<p className="inline-notice" role="status">{message}</p>}</Card><Card><div className="section-title"><div><h2>Saved broker statements</h2><p>Latest 20 uploads. Choose one report at a time; overlapping periods are never summed.</p></div><button className="button secondary" disabled={busy} onClick={load}>Load statements</button></div>{rows.length>0&&<label>Report version<select value={selected?.id||''} onChange={e=>setSelected(rows.find(r=>r.id===e.target.value)||null)}>{rows.map(r=><option key={r.id} value={r.id}>{r.payload.start} to {r.payload.end} · saved {new Date(r.created_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}</option>)}</select></label>}{selected&&<><StatementDetail statement={selected.payload} matches={matches}/><button className="button secondary" onClick={()=>downloadJson(selected,`trademirror-statement-${selected.payload.end}-${selected.id}.json`)}>Download statement JSON</button></>}</Card></>;
}
