'use client';
import {useState} from 'react';
import {listSnapshots,saveSnapshot} from '@/app/reports/actions';
import {exactMoney} from '@/lib/analytics/format';
import type {ReportMode,SavedSnapshot} from '@/lib/reports/snapshot';
export function downloadJson(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);try{a.click();}finally{a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}}
export function SavedReports({mode,date,demo=false}:{mode:ReportMode;date?:string;demo?:boolean}){
 const [rows,setRows]=useState<SavedSnapshot[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[opened,setOpened]=useState<SavedSnapshot|null>(null);
 if(demo)return <p className="fineprint">Account report snapshots are available after login. This demo does not save reports to your account.</p>;
 async function load(){setBusy(true);setMessage('');try{const result=await listSnapshots();if(result.error)setMessage(result.error);else{setRows(result.data||[]);setMessage(result.data?.length?'':'No saved snapshots yet. Save a period above.');}}catch{setMessage('Could not load saved reports. Retry.');}finally{setBusy(false);}}
 async function save(){if(!date)return;setBusy(true);setMessage('');try{const result=await saveSnapshot(mode,date);if(result.error)setMessage(result.error);else if(result.data){const saved=result.data;setRows(old=>[saved,...old.filter(x=>x.id!==saved.id)].slice(0,100));setOpened(saved);setMessage('Report snapshot saved. Existing snapshots are kept when imported history changes.');}}catch{setMessage('Could not save report. Retry.');}finally{setBusy(false);}}
 return <section className="saved-reports"><div className="section-title"><div><h2>Saved report history</h2><p>Freeze this computed gross review before your history changes.</p></div><div className="action-row"><button className="button primary" disabled={busy||!date} onClick={save}>{busy?'Working…':'Save current snapshot'}</button><button className="button secondary" disabled={busy} onClick={load}>Load saved history</button></div></div>{message&&<p role="status" className="inline-notice">{message}</p>}<p className="fineprint">Latest 100 saved snapshots. Identical period evidence reuses its existing snapshot. These are stored user reviews, not broker-certified statements. Download a snapshot to keep a portable copy.</p>{rows.length>0&&<div className="table-scroll"><table><thead><tr><th>Period</th><th>Saved · IST</th><th>Gross P&L</th><th>Review</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.mode} · {r.period}</td><td>{new Date(r.created_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}</td><td>{exactMoney(r.payload.summary.grossPnl)}</td><td><button className="text-button" onClick={()=>setOpened(r)} aria-pressed={opened?.id===r.id}>Open snapshot</button></td></tr>)}</tbody></table></div>}{opened&&<article className="snapshot-detail"><h3>{opened.mode} snapshot · {opened.period}</h3><p>{opened.payload.summary.slices} slices · {exactMoney(opened.payload.summary.grossPnl)} gross · {opened.payload.summary.winRate}% wins</p><p className="fineprint">{opened.payload.limits}</p><div className="table-scroll"><table><thead><tr><th>Exit date</th><th>Slices</th><th>Gross P&L</th></tr></thead><tbody>{opened.payload.summary.days.map(d=><tr key={d.date}><td>{d.date}</td><td>{d.slices}</td><td>{exactMoney(d.grossPnl)}</td></tr>)}</tbody></table></div><button className="button secondary" onClick={()=>downloadJson(opened,`trademirror-snapshot-${opened.period}-${opened.id}.json`)}>Download snapshot JSON</button></article>}</section>;
}
