'use server';
import {createHash} from 'node:crypto';
import {createClient} from '@/lib/supabase/server';
import {getSignedInUser} from '@/lib/auth/session';
import {workbookRows} from '@/lib/costs/xlsx';
import {parseZerodhaStatement,validateStatement,type BrokerStatement} from '@/lib/costs/zerodha';
export type StatementRecord={id:string;created_at:string;fingerprint:string;payload:BrokerStatement};
async function owner(){const user=await getSignedInUser(),client=await createClient();if(!user||!client)throw new Error('Log in again to use broker statements.');return {user,client};}
async function parsed(form:FormData){const file=form.get('file');if(!(file instanceof File)||!file.name.toLowerCase().endsWith('.xlsx')||file.size===0||file.size>5*1024*1024)throw new Error('Choose an original Zerodha F&O P&L XLSX up to 5 MB.');const bytes=Buffer.from(await file.arrayBuffer());return {payload:parseZerodhaStatement(workbookRows(bytes)),fingerprint:createHash('sha256').update(bytes).digest('hex')};}
export async function previewStatement(form:FormData):Promise<{data?:BrokerStatement;error?:string}>{try{await owner();return {data:(await parsed(form)).payload};}catch(e){return {error:e instanceof Error?e.message:'Unable to parse statement.'};}}
export async function saveStatement(form:FormData):Promise<{data?:StatementRecord;error?:string}>{try{const {user,client}=await owner();if(form.get('confirmed')!=='yes')throw new Error('Confirm this statement belongs to your account before saving.');const statement=await parsed(form);const {data,error}=await client.from('broker_statements').insert({user_id:user.id,...statement}).select('id,created_at,fingerprint,payload').single();if(error?.code==='23505'){const existing=await client.from('broker_statements').select('id,created_at,fingerprint,payload').eq('user_id',user.id).eq('fingerprint',statement.fingerprint).single();if(!existing.error)return {data:{...existing.data,payload:validateStatement(existing.data.payload)} as StatementRecord};}if(error||!data)throw new Error('Could not save the statement. Complete statement-storage setup, then retry.');return {data:{...data,payload:validateStatement(data.payload)} as StatementRecord};}catch(e){return {error:e instanceof Error?e.message:'Unable to save statement.'};}}
export async function loadStatements():Promise<{data?:StatementRecord[];error?:string}>{try{const {user,client}=await owner();const {data,error}=await client.from('broker_statements').select('id,created_at,fingerprint,payload').eq('user_id',user.id).order('created_at',{ascending:false}).order('id',{ascending:false}).limit(20);if(error)throw new Error('Statement storage is not ready. Complete setup, then reload.');return {data:(data as StatementRecord[]).map(r=>({...r,payload:validateStatement(r.payload)}))};}catch(e){return {error:e instanceof Error?e.message:'Unable to load statements.'};}}
