import Link from 'next/link';
import { getSignedInUser } from '@/lib/auth/session';
import { ArrowUpRight, ArrowRight, CalendarDays, ChartNoAxesCombined, ListFilter, ScanLine, ShieldCheck, Upload, Activity, Layers, FileDown, Check } from 'lucide-react';
import { Logo } from '@/components/dashboard/shell';
import { advancedDemo } from '@/data/advanced-demo';
import { advancedSummary } from '@/lib/analytics/advanced';
import { exactMoney } from '@/lib/analytics/format';
export const dynamic = 'force-dynamic';
export default async function Landing() {
  const signedIn = !!(await getSignedInUser());
  const sample = advancedSummary(advancedDemo.matches);
  const features = [
    { icon: ChartNoAxesCombined, title: 'Know your numbers', body: 'Gross P&L, win rate, profit factor, expectancy and closed-slice drawdown. Clear definitions behind every metric.' },
    { icon: CalendarDays, title: 'Every day tells a story', body: 'A trading calendar with daily results. Click a day to inspect the matching executions behind it.' },
    { icon: Activity, title: 'Find the patterns', body: 'Compare instruments, CE / PE, entry hours, weekdays and long / short positions using your saved history.' },
    { icon: ListFilter, title: 'One scope. Every view.', body: 'Filter dates, contracts and position sides. Your cards, charts, calendar and export update together.' },
    { icon: Layers, title: 'Executions to clarity', body: 'FIFO matching handles partial fills, short covers and reversals, with unmatched quantities shown separately.' },
    { icon: FileDown, title: 'Keep the evidence', body: 'Export filtered matching slices with exact prices, quantities, gross P&L and source execution identities.' },
  ];
  return <div className="landing advanced-landing"><header className="landing-nav"><Logo/><nav><a href="#features">Features</a><a href="#workflow">How it works</a><Link href="/demo">Live demo</Link><Link href={signedIn ? '/dashboard' : '/login'}>{signedIn ? 'Workspace' : 'Log in'}</Link><Link className="button primary" href={signedIn ? '/dashboard' : '/signup'}>{signedIn ? 'Open dashboard' : 'Start free'}<ArrowUpRight size={14}/></Link></nav></header>
    <main><section className="hero"><div className="hero-copy"><span className="eyebrow"><span className="live-dot"/> YOUR NEXT TRADING WORKSPACE</span><h1>Your trades.<br/><span>A clearer picture.</span></h1><p>Turn your Zerodha tradebook into a performance workspace. Explore the numbers, inspect every day, and understand what your history actually shows.</p><div className="hero-actions"><Link className="button primary large" href={signedIn ? '/dashboard' : '/demo'}>{signedIn ? 'Open your workspace' : 'Try the interactive demo'}<ArrowRight size={17}/></Link><Link className="button secondary large" href={signedIn ? '/import' : '/signup'}>Analyse my tradebook<Upload size={16}/></Link></div><div className="hero-trust"><span><Check size={14}/> No login for demo</span><span><Check size={14}/> Zerodha CSV imports</span><span><Check size={14}/> Exact FIFO calculations</span></div></div>
      <div className="hero-preview advanced-hero-preview"><div className="preview-top"><span><ScanLine size={17}/>TradeMirror / Performance</span><span className="badge neutral">SYNTHETIC DEMO</span></div><p className="eyebrow">REALIZED GROSS P&L</p><strong className="preview-total">{exactMoney(sample.grossPnl)}<span>Illustrative history · before charges</span></strong><div className="preview-stats"><div><small>Win rate</small><b>{sample.winRate}%</b></div><div><small>Profit factor</small><b>{sample.profitFactor}</b></div><div><small>FIFO slices</small><b>{sample.slices}</b></div></div><div className="hero-mini-calendar">{sample.days.slice(-7).map(day => <div className={day.grossPnl.startsWith('-') ? 'loss-day' : 'win-day'} key={day.date}><small>{day.date.slice(5)}</small><b>{exactMoney(day.grossPnl)}</b><span>{day.slices} slices</span></div>)}</div><div className="preview-insight"><CalendarDays size={20}/><p><b>Your daily results, connected.</b>Calendar → matching slices → exact source executions.</p></div><Link className="text-link hero-demo-link" href="/demo">Explore this workspace<ArrowUpRight size={15}/></Link></div>
    </section><div className="landing-divider"><span>LESS GUESSWORK. MORE UNDERSTANDING.</span><span>IMPORT → ANALYSE → INSPECT → REVIEW</span></div>
    <section id="features" className="landing-features"><div className="landing-section-title"><span className="eyebrow">GO BEYOND A SINGLE P&L NUMBER</span><h2>A workspace built<br/>around your history.</h2><p>Connected analytics that you can explore, filter and trace.</p></div><div className="landing-feature-grid">{features.map(item => <section className="feature" key={item.title}><item.icon size={26}/><h3>{item.title}</h3><p>{item.body}</p><span className="feature-status">Available now</span></section>)}</div></section>
    <section className="landing-data-story"><div><span className="eyebrow">CLARITY BEFORE CONFIDENCE</span><h2>Your numbers should<br/>come with an explanation.</h2><p>See what is known, what is missing, and exactly which executions contributed. TradeMirror shows gross results today; net P&L awaits confirmed broker charges.</p><Link className="text-link" href="/demo">See the calculations in action<ArrowRight size={16}/></Link></div><div className="data-story-list">{[['Exact money','Prices and P&L retain decimal precision through matching and export.'],['Your account, your history','Authenticated imports and account-owned reads keep workspaces separate.'],['Missing data stays visible','Open market values, stop-loss adherence and charges are not invented.'],['A focused roadmap','Broker charge reconciliation, persistent notes and AI-assisted reviews are planned.']].map(([title, body]) => <div key={title}><ShieldCheck size={18}/><div><h3>{title}</h3><p>{body}</p></div></div>)}</div></section>
    <section id="workflow" className="landing-workflow"><div><span className="eyebrow">FROM CSV TO A CLEARER VIEW</span><h2>Bring the history.<br/><span className="muted">Explore what happened.</span></h2><p>Zerodha Console CSV imports are active. Automatic broker sync and confirmed charge reconciliation are on the roadmap.</p><div className="broker-support"><b>Zerodha</b><span className="badge green">CSV import active</span><span className="badge neutral">Auto-sync planned</span></div></div><div className="steps">{[['01', 'Preview before saving', 'Validate your file locally. Review prices, quantities and timestamps.'],['02', 'Save to your workspace', 'Atomic import, duplicate protection and visible completion feedback.'],['03', 'Explore your performance', 'Filter analytics, inspect calendar days and review source matching slices.']].map(([number, title, body]) => <div key={number}><span>{number}</span><div><h3>{title}</h3><p>{body}</p></div></div>)}</div></section>
    <section className="landing-cta"><ChartNoAxesCombined size={30}/><span className="eyebrow">SEE IT BEFORE YOU SIGN UP</span><h2>Meet your trading mirror.</h2><p>Try the advanced workspace with clearly labelled sample data. No account required.</p><Link className="button primary large" href="/demo">Launch interactive demo<ArrowRight size={18}/></Link></section></main><footer className="landing-footer"><Logo/><span>Indian F&O journaling & performance analytics</span><span>© 2026 TradeMirror</span></footer>
  </div>;
}
