'use client';
import Link from 'next/link';
import { useActionState } from 'react';
import { requestPasswordReset, updatePassword } from '@/app/auth/actions';
import { Logo } from '@/components/dashboard/shell';
export function PasswordForm({reset=false,notice=null}:{reset?:boolean;notice?:string|null}) {
  const [state, action, pending] = useActionState(reset ? updatePassword : requestPasswordReset, {message:''});
  return <div className="auth-page"><div className="auth-story"><Logo/><div><span className="eyebrow">YOUR TRADING WORKSPACE</span><h1>Get back<br/><span className="positive">to your journal.</span></h1><p>Recover access to your TradeMirror account.</p></div><small>TradeMirror · Understand your trades. Improve your edge.</small></div><main className="auth-main"><Link href="/login" className="auth-back">← Back to login</Link><div className="auth-form"><span className="eyebrow">ACCOUNT RECOVERY</span><h1>{reset?'Set a new password.':'Forgot your password?'}</h1><p>{reset?'Choose a new password for your account.':'Enter your account email to request a password reset link.'}</p>{notice&&<p className="inline-notice" role="alert">{notice}</p>}<form action={action}>{reset?<><label>New password<input type="password" name="password" autoComplete="new-password" minLength={8} maxLength={128} required placeholder="At least 8 characters"/></label><label>Confirm new password<input type="password" name="confirmation" autoComplete="new-password" minLength={8} maxLength={128} required placeholder="Repeat your new password"/></label></>:<label>Email address<input type="email" name="email" autoComplete="email" required placeholder="you@example.com"/></label>}<button className="button primary full-width" disabled={pending||!!state.success}>{pending?'Please wait…':reset?'Update password':'Send reset link'}</button></form>{state.message&&<p className="inline-notice" role="status">{state.message}</p>}{reset&&state.success&&<Link className="button primary full-width" href="/dashboard">Go to dashboard</Link>}{!reset&&<p>Open the email link in the same browser and site where you request it. Check your spam folder too.</p>}</div></main></div>;
}
