'use client';
import { useMemo,useState } from 'react';
import { exportMatchedCsv } from '@/lib/analytics/export';
import { tradingDate } from '@/lib/analytics/daily';
import { MatchedDetail } from './matched-detail';
import { type Match,type MatchingResult } from '@/lib/analytics/matching';
const money=(value:string)=>'₹'+value;
const time=(value:string)=>new Date(value).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})+' IST';
export function AccountJournal({result,initialDay=''}:{result:MatchingResult;initialDay?:string}){
 const [selectedMatch,setSelectedMatch]=useState<Match|null>(null);const [search,setSearch]=useState('');const [side,setSide]=useState('ALL');const [outcome,setOutcome]=useState('ALL');const [page,setPage]=useState(0);const [start,setStart]=useState(initialDay);const [end,setEnd]=useState(initialDay);
 const filtered=useMemo(()=>result.matches.filter(m=>(!start||tradingDate(m.exitTime)>=start)&&(!end||tradingDate(m.exitTime)<=end)&&m.symbol.toLowerCase().includes(search.trim().toLowerCase())&&(side==='ALL'||m.side===side)&&(outcome==='ALL'||(outcome==='LOSS'?m.grossPnl.startsWith('-'):outcome==='WIN'?!m.grossPnl.startsWith('-')&&m.grossPnl!=='0':m.grossPnl==='0'))),[result.matches,search,side,outcome,start,end]);
 function download(){const url=URL.createObjectURL(new Blob([exportMatchedCsv(filtered)],{type:'text/csv;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='trademirror-fifo-matches.csv';document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const pages=Math.max(1,Math.ceil(filtered.length/50));const current=Math.min(page,pages-1);
 return <>{selectedMatch&&<MatchedDetail match={selectedMatch} onClose={()=>setSelectedMatch(null)}/>}<div className="filter-bar"><label>Exit date from <input type="date" value={start} onChange={e=>{setStart(e.target.value);setPage(0);}}/></label><label>Exit date to <input type="date" value={end} min={start||undefined} onChange={e=>{setEnd(e.target.value);setPage(0);}}/></label><label>Instrument <input aria-label="Search matched instruments" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}} placeholder="Search instrument"/></label><label>Position side <select value={side} onChange={e=>{setSide(e.target.value);setPage(0);}}><option value="ALL">All sides</option><option>LONG</option><option>SHORT</option></select></label><label>Gross result <select value={outcome} onChange={e=>{setOutcome(e.target.value);setPage(0);}}><option value="ALL">All results</option><option value="WIN">Winning</option><option value="LOSS">Losing</option><option value="ZERO">Breakeven</option></select></label><button className="button secondary" onClick={()=>{setSearch('');setSide('ALL');setOutcome('ALL');setStart('');setEnd('');setPage(0);}}>Reset filters</button></div><button className="button secondary" disabled={!filtered.length} onClick={download}>Download filtered matches</button><p>{filtered.length} matching slices · page {current+1} of {pages}</p><div className="table-scroll"><table><thead><tr><th>Instrument</th><th>Side</th><th>Quantity</th><th>Entry</th><th>Exit</th><th>Entry time</th><th>Exit time</th><th>Gross P&L</th></tr></thead><tbody>{filtered.slice(current*50,(current+1)*50).map(m=><tr key={m.id}><td><button className="text-button journal-instrument" onClick={()=>setSelectedMatch(m)}>{m.symbol}</button></td><td>{m.side}</td><td>{m.quantity}</td><td>{money(m.entryPrice)}</td><td>{money(m.exitPrice)}</td><td>{time(m.entryTime)}</td><td>{time(m.exitTime)}</td><td className={m.grossPnl.startsWith('-')?'negative':'positive'}>{money(m.grossPnl)}</td></tr>)}</tbody></table></div>{!filtered.length&&<p>No matched executions for these filters.</p>}<div className="spread"><button className="button secondary" disabled={current===0} onClick={()=>setPage(current-1)}>Previous</button><button className="button secondary" disabled={current>=pages-1} onClick={()=>setPage(current+1)}>Next</button></div></>;
}
