'use client';
import {useEffect,useState} from 'react';
import {loadAnnotation,saveAnnotation} from '@/app/journal/actions';
import {CHECKLIST,sliceIdentity,type Annotation} from '@/lib/journal/annotation';
import type {Match} from '@/lib/analytics/matching';
export function JournalEditor({match,demo=false,onDirtyChange}:{match:Match;demo?:boolean;onDirtyChange?:(dirty:boolean)=>void}){
 const [data,setData]=useState<Annotation|null>(demo?{notes:'',tags:[],checklist:[false,false,false],revision:0}:null);
 const [tags,setTags]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [dirty,setDirty]=useState(false);const [retry,setRetry]=useState(0);
 useEffect(()=>{onDirtyChange?.(dirty);},[dirty,onDirtyChange]);
 useEffect(()=>{if(demo)return;let active=true;loadAnnotation(sliceIdentity(match)).then(response=>{if(!active)return;setData(response.data||null);setTags(response.data?.tags.join(', ')||'');setMessage(response.error||'');setDirty(false);}).catch(()=>{if(active)setMessage('Unable to load saved notes. Retry loading.');});return()=>{active=false;};},[match,demo,retry]);
 async function save(){if(!data||busy)return;setBusy(true);setMessage('Saving your journal…');let response;try{response=await saveAnnotation(sliceIdentity(match),{...data,tags:tags.split(',').map(t=>t.trim()).filter(Boolean)},data.revision);}catch{setMessage('Could not confirm saving. Keep your draft; reload saved notes to check before retrying.');setBusy(false);return;}if(response.data){setData(response.data);setTags(response.data.tags.join(', '));setDirty(false);setMessage('Journal saved ✓');}else setMessage(response.error||'Unable to save. Your draft is still here.');setBusy(false);}
 return <section className="journal-editor"><h3>Your decision journal</h3><p className="fineprint">{demo?'Demo draft only · closing this view discards it.':'Notes belong to this exact matching slice. If imported history changes its prices, quantity or times, old notes will not silently attach to the new result.'}</p>{!data?<><p role="status">{message||'Loading saved notes…'}</p>{message&&<button className="button secondary" onClick={()=>{setMessage('');setRetry(retry+1);}}>Retry loading</button>}</>:<><label>Notes<textarea maxLength={10000} rows={4} value={data.notes} disabled={busy} onChange={e=>{setData({...data,notes:e.target.value});setDirty(true);}} placeholder="Why did you enter? What worked? What would you change?"/></label><label>Tags · comma separated<input value={tags} disabled={busy} onChange={e=>{setTags(e.target.value);setDirty(true);}} placeholder="breakout, planned exit"/></label><fieldset disabled={busy}><legend>Plan review · your own assessment</legend>{CHECKLIST.map((item,index)=><label key={item}><input type="checkbox" checked={data.checklist[index]} onChange={e=>{setData({...data,checklist:data.checklist.map((v,i)=>i===index?e.target.checked:v)});setDirty(true);}}/>{item}</label>)}</fieldset><p className="fineprint">Checklist answers are self-reported. They do not establish rule adherence or generate a score.</p>{!demo&&<button className="button primary" disabled={busy||!dirty} onClick={()=>void save()}>{busy?'Saving…':'Save journal'}</button>}<p role="status" aria-live="polite">{message|| (dirty?(demo?'Demo draft · closing discards your changes.':'Unsaved draft · save before closing.'):demo?'Try notes, tags and the checklist.':data.revision?'Saved journal loaded.':'No saved notes yet.')}</p>{!demo&&message&&<button className="text-link" disabled={busy} onClick={()=>{setData(null);setMessage('');setRetry(retry+1);}}>{dirty?'Discard draft and reload saved notes':'Reload saved notes'}</button>}</>}</section>;
}
