'use client';
import {useEffect,useState} from 'react';
import {loadPlan,savePlan} from '@/app/journal/actions';
import {DEFAULT_PLAN,validatePlan,type PlanTemplate} from '@/lib/journal/plan';
export function PlanEditor({demo,onPlanChange}:{demo:boolean;onPlanChange:(plan:PlanTemplate)=>void}){
 const [plan,setPlan]=useState<PlanTemplate>({name:'My trading plan',items:[...DEFAULT_PLAN],revision:0});
 const [items,setItems]=useState(DEFAULT_PLAN.join('\n'));const [message,setMessage]=useState('');const [ready,setReady]=useState(demo);const [busy,setBusy]=useState(false);const [dirty,setDirty]=useState(false);const [retry,setRetry]=useState(0);
 useEffect(()=>{if(demo)return;let active=true;loadPlan().then(response=>{if(!active)return;if(response.data){setPlan(response.data);setItems(response.data.items.join('\n'));onPlanChange(response.data);setReady(true);setDirty(false);}setMessage(response.error||'');}).catch(()=>{if(active)setMessage('Unable to load your plan. Retry loading.');});return()=>{active=false;};},[demo,retry,onPlanChange]);
 async function save(){setBusy(true);try{const content=validatePlan({name:plan.name,items:items.split('\n')});const response=demo?{data:{...content,revision:plan.revision+1}}:await savePlan(content,plan.revision);if(response.data){setPlan(response.data);setItems(response.data.items.join('\n'));onPlanChange(response.data);setDirty(false);setMessage(demo?'Demo plan updated for this page only.':'Plan template saved. Existing journal checklists keep their saved questions.');}else setMessage(response.error||'Unable to save the plan.');}catch(error){setMessage(error instanceof Error?error.message:'Could not confirm saving. Keep your draft and reload to check.');}finally{setBusy(false);}}
 return <details className="plan-settings"><summary>Customize your trading plan</summary><section className="journal-editor"><p>Set the questions you want to review. Existing entries retain their saved checklist until you explicitly replace it.</p><label>Plan name<input value={plan.name} maxLength={80} disabled={!ready||busy} onChange={e=>{setPlan({...plan,name:e.target.value});setDirty(true);}}/></label><label>Checklist questions · one per line<textarea rows={5} value={items} disabled={!ready||busy} onChange={e=>{setItems(e.target.value);setDirty(true);}}/></label><p className="fineprint">1–8 unique questions, at most 120 characters each. {demo?'Demo changes stay on this page.':'Saved privately to your account.'}</p><button className="button primary" disabled={!ready||busy||!dirty} onClick={()=>void save()}>{busy?'Saving plan…':demo?'Apply demo plan':'Save plan template'}</button><p role="status" aria-live="polite">{message||(!ready?'Loading your plan…':dirty?'Unsaved plan draft.':'Your plan is ready.')}</p>{!demo&&message&&<button className="button secondary" disabled={busy} onClick={()=>{setReady(false);setMessage('');setRetry(retry+1);}}>{dirty?'Discard plan draft and reload':'Reload plan'}</button>}</section></details>;
}
