import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft,Sparkles } from 'lucide-react';
import { trades } from '@/data/mock';
import { money,time,dateLabel } from '@/lib/analytics/format';
import { Card,Metric,SectionTitle,StatusBadge } from '@/components/ui/primitives';
import { TradeNotes } from '@/components/trades/notes';

export const dynamicParams = false;
export function generateStaticParams(){return trades.map(t=>({id:t.id}));}
export default async function TradeDetail({params}:{params:Promise<{id:string}>}){const {id}=await params;const t=trades.find(t=>t.id===id);if(!t)notFound();return <><Link className="text-link" href="/trades"><ArrowLeft size={15}/>Back to journal</Link><div className="page-heading"><div><span className="eyebrow">SAMPLE TRADE · {dateLabel(t.entryTime)}</span><h1>{t.instrument} {t.strike} <span className="muted">{t.optionType}</span></h1><p>{t.side} · Zerodha · {t.session}</p></div><StatusBadge status={t.reportStatus}/></div><div className="metric-grid detail-metrics"><Metric label="Gross P&L" value={money(t.grossPnl,true)} positive={t.grossPnl>0}/><Metric label="Estimated charges" value={money(t.charges)}/><Metric label="Estimated net P&L" value={money(t.netPnl,true)} positive={t.netPnl>0}/><Metric label="Holding time" value={`${t.holdMinutes} min`}/></div><div className="two-col"><Card><SectionTitle title="Execution details" subtitle="Normalized broker-independent fields"/><dl className="detail-list">{[['Entry price',`₹${t.entry}`],['Exit price',`₹${t.exit}`],['Quantity',`${t.quantity}`],['Entry time',`${time(t.entryTime)} IST`],['Exit time',`${time(t.exitTime)} IST`],['Report status','Provisional']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></Card><Card><SectionTitle title="Behaviour analysis" action={<span className="badge neutral">SAMPLE</span>}/><Sparkles className="positive" size={25}/><h3 className="spaced">A prompt for your review</h3><p>This sample position was held for {t.holdMinutes} minutes. Compare your intended holding period with the reason you exited before judging the decision.</p><p className="fineprint">MFE, MAE, early exit, and stop-loss adherence require additional data. No inference is made from the tradebook alone.</p></Card></div><Card><SectionTitle title="Plan & excursion metrics" subtitle="Not available in the sample tradebook"/><div className="placeholder-grid">{['MFE','MAE','Planned stop loss','Planned target','Early exit','Stop-loss violation'].map(x=><div key={x}><span>{x}</span><strong>—</strong><small>Not available</small></div>)}</div></Card><TradeNotes id={id}/></>;}
